### ISSUE TITLE
Editing firmware by myself 

### ISSUE THREAD

**Issue by samx7719** [GeekMagicClock/pixel64x32#2]
Hello, 

If I attempt to edit the firmware myself and replace it, is there a hard reset option to restore the factory settings in case something goes wrong? Can I return to the original firmware?

**Comment by GeekMagicClock** [comment]
Hello, it's not supported, and we don't offer burn firmware, so you may break it, not recommended.

**Comment by GeekMagicClock** [comment]
It should work if you could backup all the flash content, but on your own risk, be careful before change anything, no support.
