### ISSUE TITLE
Yahoo Finance discontinued - BTC price not working

### ISSUE THREAD

**Issue by miketunes** [GeekMagicClock/pixel64x32#4]
It looks like an alternate service will need to be setup: 
https://eodhd.medium.com/exploring-alternatives-to-the-yahoo-finance-api-aa0415085cc5#:~:text=While%20the%20official%20Yahoo%20Finance,based%20tools%20like%20yfinance%20exist.

**Comment by GeekMagicClock** [comment]
Yes, we plan to add alternative options for data source in future updates, but for now the api is still available.

**Comment by miketunes** [comment]
Ok - mine stopped updating the price about a week ago.  It now just says network error 404 with 0.00 as the price for bitcoin, how do I fix that?  I updated to 1.0.12 but it didn't fix it.

**Comment by GeekMagicClock** [comment]
404 means that is invalid symbol, what is the symbol you set?

**Comment by miketunes** [comment]
I tried BTC-USD, BTC, and ebay - all gave me the same error.

**Comment by GeekMagicClock** [comment]
"BTC-USD" just working fine here, which country are you in?
And can you share the screenshot of the settings on the web console about ticker?

**Comment by miketunes** [comment]
![image](https://github.com/user-attachments/assets/a5450e48-708d-49e7-8802-37f2e81435c1)

**Comment by miketunes** [comment]
Any update?  I'm in the US.

**Comment by miketunes** [comment]
Yes, I'm on V1.0.12, anything I can try?

**Comment by miketunes** [comment]
It's working now, not sure why.
